#!/usr/bin/env node
// Concert Tycoon balance simulator. Runs the real engine (no DOM) and writes
// tycoon/docs/BALANCE_BASELINE.md with PASS/FAIL verdicts.
//
//   npm run sim:tycoon
//
// The output is deterministic. CI regenerates it and fails if the committed copy
// differs, so any change to data.mjs or the rules shows up as a reviewed diff.
// Exits non-zero when a verdict fails.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as D from '../data.mjs';
import { ENGINE_VERSION, evaluateShow, evaluateVenue, rollShow } from '../engine.mjs';
import { BUDGET_LAYOUT, REFERENCE_ADS, REFERENCE_LAYOUT, REFERENCE_PRICE, WORKED_EXAMPLE } from './reference.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '../docs/BALANCE_BASELINE.md');
const lines = [];
const out = (s = '') => lines.push(s);
const verdicts = [];
const verdict = (name, pass, detail) => verdicts.push({ name, pass, detail });
const money = (n) => `${n < 0 ? '−' : ''}$${Math.abs(n).toLocaleString('en-US')}`;
const pct = (n) => `${(n * 100).toFixed(1)}%`;
const table = (head, rows) => {
  out(`| ${head.join(' | ')} |`);
  out(`| ${head.map(() => '---').join(' | ')} |`);
  rows.forEach((r) => out(`| ${r.join(' | ')} |`));
  out();
};

const ARTIST = D.ARTISTS[D.DEFAULT_ARTIST];
const MID_DRAW = Math.round((ARTIST.drawMin + ARTIST.drawMax) / 2);
const layouts = {
  reference: evaluateVenue({ objects: REFERENCE_LAYOUT }),
  budget: evaluateVenue({ objects: BUDGET_LAYOUT }),
};
const AD_PRESETS = {
  none: { flyers: 0, social: 0, radio: 0 },
  reference: REFERENCE_ADS,
  heavy: { flyers: 200, social: 500, radio: 500 },
};
const PRICES = [];
for (let p = D.PRICE_MIN; p <= D.PRICE_MAX; p += 5) PRICES.push(p);

const show = (over) => evaluateShow({
  venue: layouts.reference,
  deal: 'door',
  price: REFERENCE_PRICE,
  ads: REFERENCE_ADS,
  venueRep: 0,
  draw: MID_DRAW,
  artistId: D.DEFAULT_ARTIST,
  incidentId: null,
  responseId: null,
  ...over,
});
const better = (g, d) => (g.net > d.net ? 'guarantee' : d.net > g.net ? 'door' : 'tie');

// A strategy is playable only if its up-front money and incident response are affordable (R-12).
function playable(r, response) {
  return r.upfront <= D.START_CASH && (response ? response.cost : 0) <= D.START_CASH - r.upfront;
}

out('# Concert Tycoon Balance Baseline');
out();
out('*Generated by `npm run sim:tycoon`. Do not edit by hand. CI regenerates this file and fails if the');
out('committed copy differs, or if any verdict below is FAIL. Every number comes from `tycoon/data.mjs`');
out('through `tycoon/engine.mjs`; the layouts and strategies are fixtures in `tycoon/sim/reference.mjs`.*');
out();
out(`Engine version ${ENGINE_VERSION} · schema ${D.SCHEMA_VERSION} · artist ${ARTIST.name} (draw ${ARTIST.drawMin} to ${ARTIST.drawMax}, ask ${money(ARTIST.ask)}, fair price ${money(ARTIST.fairPrice)}) · ${D.SIM_SEEDS} seeds`);
out();

// 1. Layouts
out('## 1. Reference layouts');
out();
out('Costs use the reference ads (social $300, radio $300) and no incident response.');
out();
table(['Layout', 'Capacity', 'Limited by', 'Clear-view tiles', 'Staff', 'Power', 'Show costs', 'Up front: guarantee', 'Up front: door'],
  Object.entries(layouts).map(([name, v]) => {
    const g = show({ venue: v, deal: 'guarantee' });
    const d = show({ venue: v, deal: 'door' });
    return [name, v.capacity, v.capacityLimit, v.clearTiles, v.staff, `${v.watts} W`, money(g.costs.total), money(g.upfront), money(d.upfront)];
  }));

// 2. Draw sweep
out(`## 2. Deal outcome by draw (reference layout, ${money(REFERENCE_PRICE)} tickets, reference ads, no incident)`);
out();
const drawRows = [];
for (let draw = ARTIST.drawMin; draw <= ARTIST.drawMax; draw += 10) {
  const g = show({ draw, deal: 'guarantee' });
  const d = show({ draw, deal: 'door' });
  drawRows.push([draw, g.attendance, g.satisfaction, money(g.net), money(d.net), money(d.artistPay), better(g, d)]);
}
table(['Draw', 'Attendance', 'Satisfaction', 'Guarantee net', 'Door net', 'Door artist pay', 'Better for the promoter'], drawRows);

// 3. Price sweep
for (const draw of [MID_DRAW, ARTIST.drawMax]) {
  out(`## 3${draw === MID_DRAW ? 'a' : 'b'}. Deal outcome by ticket price (draw ${draw}, reference layout and ads, no incident)`);
  out();
  table(['Price', 'Attendance', 'Ticket gross', 'Guarantee net', 'Door net', 'Better for the promoter'],
    PRICES.map((price) => {
      const g = show({ draw, price, deal: 'guarantee' });
      const d = show({ draw, price, deal: 'door' });
      return [money(price), g.attendance, money(g.ticketGross), money(g.net), money(d.net), better(g, d)];
    }));
}

// 4. Ads
out(`## 4. Ad presets (draw ${MID_DRAW}, ${money(REFERENCE_PRICE)} tickets, no incident)`);
out();
table(['Preset', 'Spend', 'Buzz', 'Demand', 'Attendance', 'Guarantee net', 'Door net'],
  Object.entries(AD_PRESETS).map(([name, ads]) => {
    const g = show({ ads, deal: 'guarantee' });
    const d = show({ ads, deal: 'door' });
    return [name, money(d.costs.ads), d.buzz.toFixed(3), d.demand.toFixed(1), d.attendance, money(g.net), money(d.net)];
  }));

// 5. Incidents
out(`## 5. Incident responses (draw ${MID_DRAW}, reference layout, ${money(REFERENCE_PRICE)} tickets, door deal)`);
out();
const incidentRows = [];
for (const id of D.INCIDENT_ORDER) {
  for (const response of D.INCIDENTS[id].responses) {
    const r = show({ incidentId: id, responseId: response.id });
    incidentRows.push([D.INCIDENTS[id].label, response.label, money(response.cost), r.attendance, r.satisfaction, money(r.net)]);
  }
}
table(['Incident', 'Response', 'Cost', 'Attendance', 'Satisfaction', 'Door net'], incidentRows);

// 6. Seeds
const seedStats = { draws: [], incidents: Object.fromEntries(D.INCIDENT_ORDER.map((id) => [id, 0])) };
const refPass = { guarantee: { free: 0, best: 0 }, door: { free: 0, best: 0 } };
const impossible = [];
let dealWins = { guarantee: 0, door: 0 };
for (let seed = 1; seed <= D.SIM_SEEDS; seed += 1) {
  const roll = rollShow(seed);
  seedStats.draws.push(roll.draw);
  seedStats.incidents[roll.incidentId] += 1;
  const responses = D.INCIDENTS[roll.incidentId].responses;
  for (const deal of ['guarantee', 'door']) {
    const results = responses.map((response) => ({ response, r: show({ draw: roll.draw, deal, incidentId: roll.incidentId, responseId: response.id }) }));
    if (results[0].r.result === 'pass') refPass[deal].free += 1;
    if (results.some(({ response, r }) => r.result === 'pass' && playable(r, response))) refPass[deal].best += 1;
  }
  let anyPass = false;
  let bestNet = { net: -Infinity, deal: null };
  for (const deal of ['guarantee', 'door']) {
    for (const price of PRICES) {
      for (const ads of Object.values(AD_PRESETS)) {
        for (const venue of Object.values(layouts)) {
          for (const response of responses) {
            const r = show({ venue, draw: roll.draw, deal, price, ads, incidentId: roll.incidentId, responseId: response.id });
            if (!playable(r, response)) continue;
            if (r.result === 'pass') anyPass = true;
            if (r.net > bestNet.net) bestNet = { net: r.net, deal };
          }
        }
      }
    }
  }
  if (!anyPass) impossible.push(seed);
  if (bestNet.deal) dealWins[bestNet.deal] += 1;
}
const draws = seedStats.draws;
out(`## 6. Seeds 1 to ${D.SIM_SEEDS}`);
out();
out(`Draw: min ${Math.min(...draws)}, mean ${(draws.reduce((a, b) => a + b, 0) / draws.length).toFixed(1)}, max ${Math.max(...draws)}. Incidents: ${D.INCIDENT_ORDER.map((id) => `${D.INCIDENTS[id].label.toLowerCase()} ${seedStats.incidents[id]}`).join(', ')}.`);
out();
out(`Reference strategy: reference layout, ${money(REFERENCE_PRICE)} tickets, reference ads. "Free response" always picks the no-cost option; "best response" passes if any affordable response passes.`);
out();
table(['Deal', 'Pass rate, free response', 'Pass rate, best response'],
  ['guarantee', 'door'].map((deal) => [deal, pct(refPass[deal].free / D.SIM_SEEDS), pct(refPass[deal].best / D.SIM_SEEDS)]));
out(`Search grid per seed: 2 deals × ${PRICES.length} prices × ${Object.keys(AD_PRESETS).length} ad presets × ${Object.keys(layouts).length} layouts × every response. The highest-net strategy uses the door deal on ${dealWins.door} seeds and the guarantee on ${dealWins.guarantee}. Seeds with no passing strategy: ${impossible.length ? impossible.join(', ') : 'none'}.`);
out();

// Verdicts
const worked = ['guarantee', 'door'].map((deal) => evaluateShow({ ...WORKED_EXAMPLE, deal }));
verdict('Worked example matches RULES.md',
  worked[0].net === 495 && worked[1].net === 1341 && worked[0].satisfaction === 85 && worked[0].attendance === 250,
  `guarantee ${money(worked[0].net)}, door ${money(worked[1].net)}, satisfaction ${worked[0].satisfaction}, attendance ${worked[0].attendance}`);

const cliffs = [];
for (const deal of ['guarantee', 'door']) {
  let prev = null;
  for (let draw = ARTIST.drawMin; draw <= ARTIST.drawMax; draw += 1) {
    const r = show({ draw, deal });
    if (prev && r.net < prev.net) cliffs.push(`${deal} at draw ${draw}`);
    prev = r;
  }
}
verdict('More demand never lowers the net at a fixed price', cliffs.length === 0,
  cliffs.length ? `net falls: ${cliffs.slice(0, 4).join('; ')}` : `checked every draw from ${ARTIST.drawMin} to ${ARTIST.drawMax} for both deals`);

const refUpfront = show({ deal: 'guarantee' }).upfront;
verdict('The reference show is affordable on the guarantee', refUpfront <= D.START_CASH,
  `${money(refUpfront)} up front against ${money(D.START_CASH)} starting cash`);

const winners = new Set();
for (let draw = ARTIST.drawMin; draw <= ARTIST.drawMax; draw += 10) {
  for (const price of PRICES) {
    const w = better(show({ draw, price, deal: 'guarantee' }), show({ draw, price, deal: 'door' }));
    if (w !== 'tie') winners.add(w);
  }
}
verdict('Each deal is the better choice somewhere in the draw × price grid', winners.has('guarantee') && winners.has('door'),
  `better deals seen: ${[...winners].sort().join(', ') || 'none'}`);

verdict('Every seed has at least one passing strategy', impossible.length === 0,
  impossible.length ? `${impossible.length} impossible seeds` : `${D.SIM_SEEDS} of ${D.SIM_SEEDS} seeds winnable`);

const refRate = refPass.guarantee.free / D.SIM_SEEDS;
const { referencePassRateMin: lo, referencePassRateMax: hi } = D.BALANCE_TARGETS;
verdict('The guarantee with free responses is neither trivial nor hopeless', refRate >= lo && refRate <= hi,
  `${pct(refRate)} against a target of ${pct(lo)} to ${pct(hi)}`);

out('## Verdicts');
out();
table(['Check', 'Verdict', 'Detail'], verdicts.map((v) => [v.name, v.pass ? 'PASS' : '**FAIL**', v.detail]));

writeFileSync(OUT, `${lines.join('\n').trimEnd()}\n`);
const failed = verdicts.filter((v) => !v.pass);
console.log(`Wrote ${OUT}`);
for (const v of verdicts) console.log(`${v.pass ? 'PASS' : 'FAIL'}  ${v.name}: ${v.detail}`);
if (failed.length) process.exit(1);
