#!/usr/bin/env node
// Headless balance simulator. Runs the real engine formulas (no DOM, no server) and
// writes mars/docs/BALANCE_BASELINE.md with explicit PASS/FAIL verdicts.
//
//   npm run sim
//
// A regression is any method losing >10% xp/hr, any new NO SOURCE / NO SINK flag, or
// any verdict flipping to FAIL. Exits non-zero when a verdict fails, so CI catches it.
//
// The 10% rule is enforced against a committed machine-readable baseline
// (mars/docs/balance-baseline.json), not just asserted in prose: a nerf to a single
// method used to rewrite the report and still exit 0. Run with `--accept` to adopt
// the current rates as the new baseline when a change is deliberate.

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compareRateBaseline } from './baseline.mjs';
import {
  TICK_MS, TICKS_PER_SOL, NODES, BUILDINGS, BUILD_TIERS, SMELT_RECIPES, CRAFT_RECIPES,
  RESEARCH, CROPS, ITEMS, EDIBLES, STORM_TOTAL, STORM_PHASE, REGIONS, ROVERS,
  XP_TABLE, xpForLevel, createState, passiveRates, gatherTicks, smeltTicks, critChance,
} from '../engine.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SEC = TICK_MS / 1000;
const lines = [];
const out = (s = '') => lines.push(s);
const verdicts = [];
const num = (n) => n.toLocaleString('en-US');
const ACCEPT = process.argv.includes('--accept');
const BASELINE_JSON = resolve(HERE, '../docs/balance-baseline.json');
const BANDS = [1, 10, 20, 25, 30, 40, 50, 55, 65, 75, 85, 99];
const rates = {};

// Focused-play assumptions: best pick allowed at the level, Reinforced Drills from
// L30, Deep Drilling / Cryo Insulation from L55, no equipment bonuses.
function pickAt(lvl) { return lvl >= 20 ? 'laser' : lvl >= 12 ? 'titanium' : lvl >= 5 ? 'steel' : 'stone'; }

function synth(skillKey, lvl) {
  const s = createState(0);
  s.skills[skillKey] = { xp: xpForLevel(lvl), level: lvl };
  s.gear.pickaxe = pickAt(lvl);
  s.built = { ...s.built, habitat: true, machine: true };
  if (lvl >= 30) s.research.drills = true;
  if (lvl >= 55 && skillKey === 'mining') s.research.deep_drilling = true;
  if (lvl >= 55 && skillKey === 'water') s.research.cryo_insulation = true;
  return s;
}

function nodeRate(node, skillKey, lvl) {
  if (node.lvl && lvl < node.lvl) return null;
  const s = synth(skillKey, lvl);
  const need = gatherTicks(s, node);
  const crit = critChance(s, node);
  // One full node: `charges` gathers at `need` ticks each, then the respawn wait.
  const respawn = s.research.survey_markers ? 4 : 6;
  const cycleTicks = node.charges * need + respawn;
  const yieldsHr = node.charges / (cycleTicks * SEC) * 3600;
  return {
    need, crit,
    xpHr: Math.round(yieldsHr * node.xp * (1 + crit)),
    itemsHr: Math.round(yieldsHr * (node.yieldBase || 1) * (1 + crit)),
  };
}

function bestRate(skillKey, lvl) {
  const type = skillKey === 'mining' ? 'ore' : 'ice';
  let best = null;
  // Basin nodes only — off-region nodes cost fuel and travel the focused sim ignores.
  for (const n of NODES.filter((n) => n.type === type && !n.regionId)) {
    const r = nodeRate(n, skillKey, lvl);
    if (r && (!best || r.xpHr > best.xpHr)) best = { node: n, ...r };
  }
  return best;
}

out('# MarsScape Balance Baseline');
out('');
out('*Generated by `npm run sim`. Do not edit by hand. Regenerate after any data or');
out('formula change; a regression is any method losing >10% xp/hr, any new NO SOURCE /');
out('NO SINK flag, or any verdict flipping to FAIL.*');
out('');
out(`Tick = ${TICK_MS} ms · Sol = ${TICKS_PER_SOL} ticks · XP curve: RuneScape (99 = ${num(XP_TABLE[99])} xp)`);
out('');
out('Focused-play assumptions: best pick allowed at each level (steel@5, titanium@12,');
out('laser@20), Reinforced Drills from L30, Deep Drilling / Cryo Insulation from L55, no');
out('equipment bonuses — gear makes real play faster than these tables.');
out('');

/* 1. gathering ------------------------------------------------------------- */
for (const [skillKey, label] of [['mining', 'Mining'], ['water', 'Ice Harvesting']]) {
  out(`## ${label}: best method by level band`);
  out('');
  out('| Level | Best method | Ticks | Quality | xp/hr | items/hr |');
  out('|---|---|---:|---:|---:|---:|');
  rates[skillKey] = {};
  for (const lvl of BANDS) {
    const b = bestRate(skillKey, lvl);
    rates[skillKey][lvl] = b.xpHr;
    out(`| ${lvl} | ${b.node.name} | ${b.need} | ${(b.crit * 100).toFixed(1)}% | ${num(b.xpHr)} | ${num(b.itemsHr)} |`);
  }
  out('');
  const flat = [];
  for (let l = 1; l <= 89; l += 1) {
    if (bestRate(skillKey, l).xpHr === bestRate(skillKey, l + 10).xpHr) flat.push(l);
  }
  verdicts.push([`${label} flattening check`, flat.length === 0]);
  out(`**Flattening check:** ${flat.length === 0
    ? '**PASS** — best-method xp/hr differs across every 10-level gap.'
    : `**FAIL** at levels ${flat.join(', ')}`}`);
  out('');
}

/* 2. time to 99 ------------------------------------------------------------ */
let hours = 0;
const bandHours = [];
for (let l = 1; l < 99; l += 1) {
  hours += (XP_TABLE[l + 1] - XP_TABLE[l]) / bestRate('mining', l).xpHr;
  if ([10, 25, 30, 50, 55, 75, 90, 98].includes(l)) bandHours.push([l + 1, hours]);
}
out('## Mining: time to level (focused, no idle)');
out('');
out('| Milestone | Cumulative hours |');
out('|---|---:|');
for (const [l, h] of bandHours) out(`| Level ${l} | ${h.toFixed(1)} |`);
out('');
const paceOk = hours >= 30 && hours <= 40;
verdicts.push(['Mining 99 in 30-40 focused hours', paceOk]);
out(`**Time-to-99:** ${hours.toFixed(1)} focused hours — ${paceOk ? '**PASS** (30-40h target)' : '**FAIL** (target 30-40h)'}.`);
out('');

/* 3. smelting -------------------------------------------------------------- */
out('## Smelting (Fabrication)');
out('');
out('| Recipe | Ticks (T1) | Ticks (T3 + loaders) | xp/hr T1 | xp/hr best |');
out('|---|---:|---:|---:|---:|');
for (const rec of SMELT_RECIPES) {
  const s1 = createState(0);
  const s3 = createState(0);
  s3.tier.machine = 3;
  s3.research.loaders = true;
  const base = smeltTicks(s1, rec);
  const fast = smeltTicks(s3, rec);
  out(`| ${rec.name} | ${base} | ${fast} | ${num(Math.round(rec.xp / (base * SEC) * 3600))} | ${num(Math.round(rec.xp / (fast * SEC) * 3600))} |`);
}
out('');

/* 4. resource flow --------------------------------------------------------- */
out('## Resource flow (sources → sinks)');
out('');
const flow = {};
for (const id of Object.keys(ITEMS)) flow[id] = { src: new Set(), snk: new Set() };
NODES.forEach((n) => flow[n.item]?.src.add('node'));
flow.geode.src.add('mining (quality find)');
SMELT_RECIPES.forEach((r) => {
  Object.keys(r.input).forEach((k) => flow[k].snk.add('smelt'));
  Object.keys(r.output).forEach((k) => flow[k].src.add('smelt'));
});
CRAFT_RECIPES.forEach((r) => {
  Object.keys(r.input).forEach((k) => flow[k].snk.add(`craft:${r.name}`));
  if (r.output) Object.keys(r.output).forEach((k) => flow[k].src.add('craft'));
});
BUILDINGS.forEach((b) => Object.keys(b.cost || {}).forEach((k) => flow[k].snk.add('build')));
Object.values(BUILD_TIERS).forEach((tiers) => tiers.forEach((t) => Object.keys(t.cost).forEach((k) => flow[k].snk.add('upgrade'))));
RESEARCH.forEach((r) => Object.keys(r.input).forEach((k) => flow[k].snk.add(`research:${r.name}`)));
CROPS.forEach((c) => { flow[c.item].src.add('farm'); flow.water.snk.add('planting'); });
Object.keys(EDIBLES).forEach((k) => flow[k].snk.add('ration (O2)'));
['iron_ore', 'copper_ore', 'ice', 'titanium_ore', 'component', 'silicate_ore', 'geode'].forEach((k) => flow[k].src.add('trek'));
flow.water.src.add('water plant');
flow.ice.snk.add('water plant');
flow.fertilizer.snk.add('planting');
flow.fuel.snk.add('rover travel');
flow.water.snk.add('fuel refining');
let flags = 0;
out('| Item | Sources | Sinks | Flags |');
out('|---|---|---|---|');
for (const [id, f] of Object.entries(flow)) {
  const bad = [];
  if (!f.src.size) { bad.push('**NO SOURCE**'); flags += 1; }
  if (!f.snk.size) { bad.push('**NO SINK**'); flags += 1; }
  out(`| ${ITEMS[id].name} | ${[...f.src].slice(0, 4).join(', ') || '—'} | ${[...f.snk].slice(0, 4).join(', ') || '—'} | ${bad.join(' ') || 'ok'} |`);
}
verdicts.push(['Zero NO SOURCE / NO SINK flags', flags === 0]);
out('');
out(`**Flow check:** ${flags === 0 ? '**PASS** — every item has a source and a sink.' : `**FAIL** — ${flags} flags above.`}`);
out('');

/* 5. survival equilibrium -------------------------------------------------- */
out('## Survival equilibrium (passive rates / tick)');
out('');
out('| Colony stage | O2 | Power |');
out('|---|---:|---:|');
const stages = [
  ['Habitat only (start)', { habitat: true }, {}, {}],
  ['+ Solar I', { habitat: true, solar: true }, {}, {}],
  ['+ Solar III + Habitat III', { habitat: true, solar: true }, { habitat: 3, solar: 3 }, {}],
  ['Full colony, all research', { habitat: true, solar: true, greenhouse: true, reactor: true },
    { habitat: 3, solar: 3, greenhouse: 3 }, { scrubbers: true, thermal_recyclers: true, grid_buffers: true }],
];
for (const [label, built, tier, research] of stages) {
  const s = createState(0);
  s.built = { ...s.built, ...built };
  s.tier = { ...s.tier, ...tier };
  s.research = { ...s.research, ...research };
  const r = passiveRates(s);
  out(`| ${label} | ${r.oxygen >= 0 ? '+' : ''}${r.oxygen.toFixed(3)} | ${r.power >= 0 ? '+' : ''}${r.power.toFixed(3)} |`);
}
out('');

/* 6. travel ---------------------------------------------------------------- */
out('## Travel: rover and Piloting cut cross-region time');
out('');
const dest = Object.keys(REGIONS).find((id) => !REGIONS[id].home);
function travelTicksFor(rover, lvl) {
  const region = REGIONS[dest];
  const s = createState(0);
  s.rover = rover;
  s.skills.piloting = { xp: xpForLevel(lvl), level: lvl };
  const geared = Math.round(region.baseTravelTicks * ROVERS[rover].mult);
  return Math.max(4, geared - Math.floor(lvl / 8));
}
out('| Destination | Rover | Piloting 1 | Piloting 40 | Piloting 99 |');
out('|---|---|---:|---:|---:|');
for (const rover of Object.keys(ROVERS)) {
  const cells = [1, 40, 99].map((lvl) => `${travelTicksFor(rover, lvl)} ticks`);
  out(`| ${REGIONS[dest].name} | ${ROVERS[rover].name} | ${cells[0]} | ${cells[1]} | ${cells[2]} |`);
}
const travelPass = travelTicksFor('rover3', 1) < travelTicksFor('buggy', 1)
  && travelTicksFor('buggy', 40) < travelTicksFor('buggy', 1);
verdicts.push(['Rover and Piloting measurably cut travel time', travelPass]);
out('');
out(`**Travel check:** ${travelPass ? '**PASS** — both a better rover and higher Piloting strictly reduce travel time.' : '**FAIL**'}`);
out('');

/* 7. the Great Storm ------------------------------------------------------- */
out('## The Great Storm');
out('');
out(`${STORM_TOTAL} ticks, 10 phases of ${STORM_PHASE}. The Survival ladder (low-O2 grace at 25,`);
out('surge softening at 40, emergency beacon at 50) plus suit O2 efficiency give late-game');
out('colonists real storm tools.');
out('');

/* regression check against the committed baseline ---------------------------- */
let baseline = null;
if (existsSync(BASELINE_JSON)) {
  try { baseline = JSON.parse(readFileSync(BASELINE_JSON, 'utf8')); } catch { baseline = null; }
}
const REGRESSION_THRESHOLD = 0.10;
const comparison = ACCEPT
  ? { ok: true, problems: [] }
  : compareRateBaseline(baseline, rates, REGRESSION_THRESHOLD);
out('## Regression check (vs committed baseline)');
out('');
if (ACCEPT) {
  out('The current rates were explicitly accepted as the new committed baseline.');
} else if (comparison.ok) {
  out(`No method lost more than ${REGRESSION_THRESHOLD * 100}% xp/hr against the committed baseline.`);
} else {
  const drops = comparison.problems.filter((problem) => problem.kind === 'regression');
  if (drops.length) {
    out('| Method | Level | Baseline xp/hr | Now | Change |');
    out('|---|---:|---:|---:|---:|');
    for (const drop of drops) out(`| ${drop.skillKey} | ${drop.level} | ${num(drop.prior)} | ${num(drop.current)} | ${drop.pct.toFixed(1)}% |`);
    out('');
  }
  for (const problem of comparison.problems.filter((entry) => entry.kind !== 'regression')) {
    out(`- **FAIL** — ${problem.message}`);
  }
  out(`**FAIL** — ${comparison.problems.length} committed-baseline check(s) failed.`);
  out('If the change is deliberate, re-run with `npm run sim -- --accept`.');
}
verdicts.push([`No method lost more than ${REGRESSION_THRESHOLD * 100}% xp/hr`, comparison.ok]);
out('');

/* verdicts ----------------------------------------------------------------- */
out('## Verdicts');
out('');
for (const [name, ok] of verdicts) out(`- ${ok ? 'PASS' : 'FAIL'} — ${name}`);
out('');

mkdirSync(resolve(HERE, '../docs'), { recursive: true });
// Trim trailing blanks so the file ends with exactly one newline — otherwise every
// regeneration reintroduces a `new blank line at EOF` that `git diff --check` flags.
while (lines.length && lines[lines.length - 1] === '') lines.pop();
writeFileSync(resolve(HERE, '../docs/BALANCE_BASELINE.md'), `${lines.join('\n')}\n`);
console.log('wrote mars/docs/BALANCE_BASELINE.md');

// Only write the machine baseline when the change is explicitly accepted — a missing
// baseline is a CI failure, not permission to recreate the evidence being checked.
if (ACCEPT) {
  writeFileSync(BASELINE_JSON, `${JSON.stringify({ threshold: REGRESSION_THRESHOLD, rates }, null, 2)}\n`);
  console.log(`wrote mars/docs/balance-baseline.json${ACCEPT ? ' (accepted)' : ''}`);
}
for (const [name, ok] of verdicts) console.log(`${ok ? 'PASS' : 'FAIL'} - ${name}`);
process.exit(verdicts.some(([, ok]) => !ok) ? 1 : 0);
