// Front of House reference generator: writes docs/ASSETS.md, docs/CATALOG.md and docs/STRINGS.md.
//
// Run with `npm run docs:front-of-house`. Every table comes from the code (data.mjs, engine.mjs,
// board.js, game.js) or from the hand-kept asset register (sprites/manifest.mjs), so the documents
// cannot drift: CI regenerates them and fails if the committed copies differ. The script exits
// non-zero when the code and the register disagree (an unlisted image, a listed file that is
// missing, an action with no description), so a stale register fails the build too.

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, resolve } from 'node:path';
import vm from 'node:vm';
import * as D from '../data.mjs';
import * as E from '../engine.mjs';
import { LOOK, SPRITE_FIT } from '../board.js';
import * as M from '../sprites/manifest.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..'); // front-of-house/
const REPO = resolve(ROOT, '..');
const DOCS = join(ROOT, 'docs');
const problems = [];
const problem = (msg) => problems.push(msg);

const HEADER = (title, what) => `# ${title}

*Generated by \`npm run docs:front-of-house\` (\`front-of-house/tools/docs.mjs\`). Do not edit by hand. CI regenerates
this file and fails if the committed copy differs. ${what}*
`;
const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (head, rows) => [
  `| ${head.join(' | ')} |`,
  `| ${head.map(() => '---').join(' | ')} |`,
  ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`),
].join('\n');
const usd = (n) => `$${Number(n).toLocaleString('en-US')}`;
const kb = (bytes) => `${(bytes / 1024).toFixed(1)}`;
const clockAt = (share) => {
  const m = 19 * 60 + Math.round(share * 240); // doors 19:00 to curfew 23:00, as game.js clock()
  return `${String(Math.floor(m / 60)).padStart(2, '0')}:${String(m % 60).padStart(2, '0')}`;
};

// PNG width and height from the IHDR chunk, so the script needs no image library.
function pngSize(file) {
  const b = readFileSync(file);
  if (b.length < 24 || b.toString('ascii', 1, 4) !== 'PNG') return null;
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20), bytes: b.length };
}

// ---------------------------------------------------------------------------
// ASSETS.md

function assetsDoc() {
  const spritesDir = join(ROOT, 'sprites');
  const libDir = join(spritesDir, 'library');
  const boardFiles = readdirSync(spritesDir).filter((f) => f.endsWith('.png')).map((f) => f.slice(0, -4)).sort();
  const libFiles = readdirSync(libDir).filter((f) => f.endsWith('.png')).map((f) => f.slice(0, -4)).sort();

  for (const id of boardFiles) if (!M.BOARD_SPRITES[id]) problem(`sprites/${id}.png is not in sprites/manifest.mjs BOARD_SPRITES`);
  for (const id of Object.keys(M.BOARD_SPRITES)) {
    if (!boardFiles.includes(id)) problem(`BOARD_SPRITES.${id} has no file sprites/${id}.png`);
    if (!SPRITE_FIT[id]) problem(`BOARD_SPRITES.${id} has no prop in board.js PROPS`);
    if (!D.OBJECT_TYPES[id]) problem(`BOARD_SPRITES.${id} is not an object type in data.mjs`);
    if (!M.STATUS[M.BOARD_SPRITES[id].status]) problem(`BOARD_SPRITES.${id} has an unknown status`);
  }
  for (const id of Object.keys(SPRITE_FIT)) if (!M.BOARD_SPRITES[id]) problem(`board.js PROPS.${id} has no entry in BOARD_SPRITES`);
  for (const id of libFiles) if (!M.LIBRARY[id]) problem(`sprites/library/${id}.png is not in sprites/manifest.mjs LIBRARY`);
  for (const id of Object.keys(M.LIBRARY)) if (!libFiles.includes(id)) problem(`LIBRARY.${id} has no file sprites/library/${id}.png`);

  let boardBytes = 0;
  const boardRows = Object.keys(M.BOARD_SPRITES).sort().map((id) => {
    const a = M.BOARD_SPRITES[id];
    const t = D.OBJECT_TYPES[id] || {};
    const size = existsSync(join(spritesDir, `${id}.png`)) ? pngSize(join(spritesDir, `${id}.png`)) : null;
    if (size) boardBytes += size.bytes;
    const fit = SPRITE_FIT[id] || {};
    const fitText = [fit.w !== undefined ? `w ${fit.w}` : null, fit.h !== undefined ? `h ${fit.h}` : null, fit.foot !== undefined ? `foot ${fit.foot}` : null, fit.lamp !== undefined ? `lamp ${fit.lamp}` : null].filter(Boolean).join(', ');
    return [`\`${id}\``, t.label, `\`sprites/${id}.png\``, size ? `${size.w} × ${size.h}` : 'missing', size ? kb(size.bytes) : '', `${t.w} × ${t.h}`, fitText, LOOK[id] ? LOOK[id].height : '', a.status, `\`${a.added}\``, a.source];
  });

  let libBytes = 0;
  const libRows = Object.keys(M.LIBRARY).sort().map((id) => {
    const a = M.LIBRARY[id];
    const file = join(libDir, `${id}.png`);
    const size = existsSync(file) ? pngSize(file) : null;
    if (size) libBytes += size.bytes;
    return [`\`${id}\``, a.subject, size ? `${size.w} × ${size.h}` : 'missing', size ? kb(size.bytes) : '', a.use];
  });

  const otherRows = M.OTHER_ASSETS.map((a) => {
    const abs = a.path.startsWith('/') ? join(REPO, a.path) : resolve(ROOT, a.path);
    const ok = existsSync(abs);
    if (!ok) problem(`OTHER_ASSETS ${a.path} does not exist`);
    return [`\`${a.path}\``, a.kind, ok ? kb(statSync(abs).size) : 'missing', a.note];
  });

  return `${HEADER('Front of House Asset Manifest', 'Image sizes are measured from the files; status, subject and source come from `sprites/manifest.mjs`.')}
Every image, drawing and sound the game uses or keeps, with where it lives and whether it is final. To add or replace an image: put the file in \`sprites/\`, add it to \`sprites/manifest.mjs\`, add its prop to \`PROPS\` in \`board.js\` if the board draws it, then run \`npm run docs:front-of-house\`.

## Summary

${table(['Group', 'Files', 'Size (KB)', 'Status'], [
    ['Board sprites (`sprites/`)', boardRows.length, kb(boardBytes), 'Stand-in'],
    ['Sprite library (`sprites/library/`)', libRows.length, kb(libBytes), 'Library, drawn by nothing'],
    ['Code-drawn elements (`board.js`)', M.CODE_DRAWN.length, '0', 'Drawn every frame'],
    ['Sound', M.AUDIO.length, '0', M.AUDIO.length ? '' : 'None yet'],
  ])}

## 1. Board sprites

The board draws these over each object's footprint once all of them have decoded. If any file fails, every prop keeps its code-drawn box. *Fit* is the sprite's geometry from \`PROPS\` in \`board.js\` (\`w\` or \`h\` as a share of the footprint's screen size, \`foot\` where the footprint sits in the image, \`lamp\` the light tower's beam origin). *Box h* is the fallback box height in tiles.

${table(['Id', 'Object', 'File', 'Pixels', 'KB', 'Footprint', 'Fit', 'Box h', 'Status', 'Added', 'Source'], boardRows)}

The fence kit is the only object type with no sprite: it is a site-wide purchase, not a placed prop.

## 2. Sprite library

Added in \`${M.LIBRARY_ADDED}\` for later tiers. Nothing draws these yet, and the service worker does not precache them. *First use* is a suggestion from [FUTURE.md](FUTURE.md#systems-and-the-first-tier-that-needs-them), not a decision. They are high-detail renders, not the pixel sheets [ART_DIRECTION.md](ART_DIRECTION.md) calls for, and the two crowd groups are in a different, cartoon style from the props.

${table(['Id', 'Subject', 'Pixels', 'KB', 'First use'], libRows)}

## 3. Drawn in code

${table(['Element', 'Where', 'Note'], M.CODE_DRAWN.map((c) => [c.name, c.where, c.note]))}

## 4. Other files

${table(['Path', 'Kind', 'KB', 'Note'], otherRows)}

## 5. Sound

${M.AUDIO.length ? table(['Id', 'File', 'Trigger'], M.AUDIO.map((a) => [a.id, a.file, a.trigger])) : 'None. The header\'s Mute All button belongs to the shared studio navigation; Front of House plays no sound.'}

## 6. Status key

${table(['Status', 'Meaning'], Object.entries(M.STATUS).map(([k, v]) => [k, v]))}
`;
}

// ---------------------------------------------------------------------------
// CATALOG.md

// One line per phase: the screen that shows it and what the save must hold to be in it
// (supportsPhase in engine.mjs). A phase added to PHASES without a line here fails the build.
const PHASE_NOTES = {
  book: { screen: 'Book sheet: rooms, nights, two offer cards', holds: 'Nothing; a new game starts here' },
  build: { screen: 'Build: full board with corner HUD', holds: 'A deal is chosen' },
  promote: { screen: 'Promote sheet: price, ads, forecast, presales', holds: 'A deal, and a venue that passes R-18' },
  show: { screen: 'Show: night board, clock, incident card, feed', holds: 'Promotion confirmed and a show with its incident' },
  settle: { screen: 'Settle: summary, then the settlement window', holds: 'The incident has a response' },
  done: { screen: 'Done sheet: career goal, history, next show', holds: 'At least one settled show' },
};

// What each engine action is for. An action in applyAction without a line here fails the build.
const ACTION_NOTES = {
  enableEquipment: 'Enable explicit ownership and open the optional cash journal at current cash',
  equipment: 'Buy or sell a small PA between bookings with a stable transaction identity',
  assignEquipment: 'Assign an owned small PA in Build or return to rental; freezes at doors',
  enableResearch: 'Enable optional development after the first settled show; Sandbox starts learned',
  research: 'Start, pause, resume or cancel a project between bookings; exact career cash delta',
  chooseDeal: 'Book an act on a deal; the deal and terms are fixed here',
  chooseVenue: 'Switch room before booking; each room keeps its own layout',
  place: 'Place one object, checked against R-18',
  setLayout: 'Replace the whole layout (Suggested layout, Clear)',
  remove: 'Remove the object at a list index',
  confirmBuild: 'Lock the layout once the venue is ready',
  setPromotion: 'Set ticket price, ad spend and (with seats) seat price',
  confirmPromotion: 'Pay what is due before doors and open them; rolls the incident',
  advanceLive: 'Live pilot: advance whole game minutes, pausing at the unanswered incident',
  assignLiveWorker: 'Live pilot: transfer the worker between admission and bar',
  chooseDoorCrew: 'Opt-in doors trial only: put the spare worker on the bar or the gate',
  respond: 'Answer the incident; pays its cost',
  acceptSettlement: 'Sign the sheet: cash, history, reputation, unlocks; next night of a run',
  back: 'Step back from Build to Book, or Promote to Build',
  nextShow: 'Start the next show, carrying cash, reputation, unlocks and history',
  retry: 'Start over: a new career that keeps only the layouts',
};

// Refusals whose text is computed rather than written out: what the player sees instead.
const FAIL_EXPLAIN = {
  'result.error': 'The service, research or equipment model refusal, including eligibility, funds and duplicate identity conflicts',
  'mine.message': 'The placement problem for this object, from `validateLayout` (R-18)',
  'problems[0].message': 'The first placement problem in the layout, from `validateLayout` (R-18)',
  "[...v.missing, ...v.problems.map((p) => p.message)].join('; ') || 'The venue has no capacity'":
    'Every missing requirement and placement problem, joined with "; " (R-18); "The venue has no capacity" if there are none',
};

// Every fail(state, …) call in a case: its argument (brackets balanced), the literal texts in it,
// and the action it is limited to when it sits under `if (action.type === '…' …)`.
function failCalls(seg) {
  const out = [];
  let from = 0;
  for (;;) {
    const at = seg.indexOf('fail(state, ', from);
    if (at < 0) break;
    let i = at + 'fail(state, '.length;
    const argStart = i;
    let depth = 1;
    let quote = null;
    for (; i < seg.length; i += 1) {
      const c = seg[i];
      if (quote) { if (c === quote && seg[i - 1] !== '\\') quote = null; continue; }
      if (c === "'" || c === '`' || c === '"') { quote = c; continue; }
      if (c === '(' || c === '[' || c === '{') depth += 1;
      if (c === ')' || c === ']' || c === '}') { depth -= 1; if (depth === 0) break; }
    }
    const arg = seg.slice(argStart, i).replace(/\s+/g, ' ').trim();
    from = i;
    if (arg === 'err') continue;
    const lineStart = seg.lastIndexOf('\n', at);
    const ifLine = seg.slice(seg.lastIndexOf('\n', lineStart - 1), lineStart);
    const only = (ifLine.match(/action\.type === '([A-Za-z]+)'/) || [])[1] || null;
    const literals = [...arg.matchAll(/'([^']*)'|`([^`]*)`/g)].map((x) => x[1] ?? x[2]);
    if (/^['`][^'`]*['`]$/.test(arg)) out.push({ text: literals[0], only });
    else if (FAIL_EXPLAIN[arg]) out.push({ text: FAIL_EXPLAIN[arg], computed: true, only });
    else if (/\?/.test(arg) && literals.length > 1) literals.forEach((t) => out.push({ text: t, only }));
    else { problem(`tools/docs.mjs cannot read the refusal \`${arg}\`; add it to FAIL_EXPLAIN`); }
  }
  return out;
}

// Split applyAction's switch into its cases and read each one's rules from the source.
function parseActions() {
  const src = readFileSync(join(ROOT, 'engine.mjs'), 'utf8');
  const start = src.indexOf('function applyActionCore(');
  const end = src.indexOf('\n}\n', start);
  const body = src.slice(start, end);
  const re = /\n {4}case '([A-Za-z]+)':/g;
  const marks = [];
  let m;
  while ((m = re.exec(body))) marks.push({ id: m[1], at: m.index });
  const defaultAt = body.indexOf('\n    default:');
  const actions = {};
  marks.forEach((mk, i) => {
    const seg = body.slice(mk.at, i + 1 < marks.length ? marks[i + 1].at : defaultAt);
    actions[mk.id] = {
      seg,
      need: [...seg.matchAll(/need\('([a-z]+)'\)/g)].map((x) => x[1]),
      to: [...new Set([...seg.matchAll(/s\.phase = '([a-z]+)'/g)].map((x) => x[1]))],
      fields: [...new Set([...seg.matchAll(/action\.([A-Za-z]+)/g)].map((x) => x[1]).filter((f) => f !== 'type'))],
      fails: failCalls(seg),
    };
  });
  // Cases that share a body (nextShow and retry) take the body of the case they fall into.
  for (const [id, a] of Object.entries(actions)) {
    if (!a.need.length && !a.to.length && !a.fails.length && a.seg.trim().split('\n').length <= 1) {
      const next = marks[marks.findIndex((x) => x.id === id) + 1];
      if (next) actions[id] = { ...actions[next.id], fallsInto: next.id };
    }
  }
  return actions;
}

function stateInShow() {
  return [{ type: 'chooseDeal', deal: 'door' }, { type: 'setLayout', objects: D.STARTER_LAYOUT }, { type: 'confirmBuild' }, { type: 'confirmPromotion' }]
    .reduce((st, a) => E.applyAction(st, a).state, E.createGame(42));
}

// Run each action from a reference state in each phase and record what happens.
function transitionMatrix(actionIds) {
  const run = (s, list) => list.reduce((st, a) => {
    const r = E.applyAction(st, a);
    if (r.error) throw new Error(`reference path failed at ${a.type}: ${r.error}`);
    return r.state;
  }, s);
  const book = E.createGame(42);
  const build = run(book, [{ type: 'chooseDeal', deal: 'door' }, { type: 'setLayout', objects: D.STARTER_LAYOUT }]);
  const promote = run(build, [{ type: 'confirmBuild' }]);
  const show = run(promote, [{ type: 'confirmPromotion' }]);
  const firstResponse = D.INCIDENTS[show.show.incidentId].responses[0].id;
  const settle = run(show, [{ type: 'respond', responseId: firstResponse }]);
  const done = run(settle, [{ type: 'acceptSettlement' }]);
  const states = { book, build, promote, show, settle, done };
  const payload = {
    enableEquipment: {},
    equipment: { command: { id: 'reference_buy', kind: 'buy', family: 'small-pa' } },
    assignEquipment: { assetId: null },
    enableResearch: {},
    research: { command: { kind: 'start', project: 'patch' } },
    chooseDeal: { deal: 'door' },
    chooseVenue: { venueId: 'lot' },
    place: { object: { type: 'restroom', x: 5, y: 10, rot: 0 } },
    setLayout: { objects: D.STARTER_LAYOUT },
    remove: { index: 0 },
    confirmBuild: {},
    setPromotion: { price: 20 },
    confirmPromotion: {},
    chooseDoorCrew: { choice: 'gate' },
    advanceLive: { minute: 5 },
    assignLiveWorker: { station: 'gate' },
    respond: { responseId: firstResponse },
    acceptSettlement: {},
    back: {},
    nextShow: {},
    retry: {},
  };
  for (const id of actionIds) if (!payload[id]) problem(`tools/docs.mjs has no reference payload for action ${id}`);
  const rows = E.PHASES.map((phase) => [phase, ...actionIds.map((id) => {
    const r = E.applyAction(states[phase], { type: id, ...(payload[id] || {}) });
    if (r.error) return '✗';
    return r.state.phase === phase ? '✓' : `→ ${r.state.phase}`;
  })]);
  return { rows, firstResponse };
}

function catalogDoc() {
  for (const p of E.PHASES) if (!PHASE_NOTES[p]) problem(`PHASE_NOTES in tools/docs.mjs has no line for phase ${p}`);
  const actions = parseActions();
  const ids = Object.keys(actions);
  for (const id of ids) if (!ACTION_NOTES[id]) problem(`ACTION_NOTES in tools/docs.mjs has no line for action ${id}`);
  for (const id of Object.keys(ACTION_NOTES)) if (!actions[id]) problem(`ACTION_NOTES.${id} is not an action in engine.mjs`);
  const { rows: matrix, firstResponse } = transitionMatrix(ids);

  const allowed = (id) => {
    const a = actions[id];
    if (a.need.length) return a.need.join(', ');
    if (['enableResearch', 'research', 'enableEquipment', 'equipment'].includes(id)) return 'book, done (eligibility required)';
    if (id === 'back') return 'build, promote';
    return 'any';
  };
  const actionRows = ids.map((id) => {
    const a = actions[id];
    let to = a.to.length ? a.to.join(' or ') : 'stays';
    if (id === 'nextShow' || id === 'retry') to = 'book (a new show state)';
    const own = a.fails.filter((f) => !f.only || f.only === id);
    return [`\`${id}\``, ACTION_NOTES[id] || '', a.fields.length ? a.fields.map((f) => `\`${f}\``).join(', ') : '—', allowed(id), to, own.length];
  });
  const failRows = ids.flatMap((id) => (actions[id].fallsInto ? [] : actions[id].fails.map((f) => [
    `\`${f.only || id}\``, f.computed ? `*${f.text}*` : f.text,
  ])));

  const modes = [
    ['career', E.createGame(1)],
    ['sandbox', E.createGame(1, { mode: 'sandbox' })],
    ['scenario: wet-lot', E.createGame(1, { mode: 'scenario', scenario: 'wet-lot' })],
  ].map(([name, g]) => [name, usd(g.cash), g.forcedIncident || '—', g.venue.objects.length ? 'Suggested layout placed' : 'Empty lot',
    Object.entries(g.unlocks).filter(([k, v]) => v && k !== 'complete').map(([k]) => D.VENUES[k].name).join(', ') || 'Lot only']);

  const goals = { lot: D.LOT_GOAL, club: D.CLUB_GOAL, amphitheater: D.AMP_GOAL, festival: D.FEST_GOAL };
  const goalText = (g) => Object.entries(g).map(([k, v]) => (k === 'cash' ? `${usd(v)} cash` : k === 'venueRep' ? `venue rep ${v}` : k === 'loyalAct' ? `an act at +${v}` : k === 'sellouts' ? `${v} sellout` : k === 'attendance' ? `${v.toLocaleString('en-US')} attending` : `${k} ${v}`)).join(' · ');
  const roomRows = D.VENUE_ORDER.map((id) => {
    const v = D.VENUES[id];
    return [v.name, `\`${id}\``, v.tier, `${v.grid.w} × ${v.grid.h}`, v.permit.toLocaleString('en-US'), `${v.watts / 1000} kW`, usd(v.rental + v.permitFee),
      v.housePa ? `House ${v.housePa}` : 'Rent', v.seats || '—', v.nights.join(', '), (v.incidents || D.INCIDENT_ORDER).join(', '),
      v.roster.map((a) => D.ARTISTS[a].name).join(', '), goalText(goals[id])];
  });

  const roomsWith = (inc) => D.VENUE_ORDER.filter((id) => (D.VENUES[id].incidents || D.INCIDENT_ORDER).includes(inc)).map((id) => D.VENUES[id].name).join(', ') || 'None (forced only)';
  const incidentRows = Object.entries(D.INCIDENTS).map(([id, inc]) => [`\`${id}\``, inc.label,
    inc.window ? `${inc.window[0]} to ${inc.window[1]} (${clockAt(inc.window[0])} to ${clockAt(inc.window[1])})` : 'missing', roomsWith(id)]);
  for (const [id, inc] of Object.entries(D.INCIDENTS)) if (!inc.window) problem(`INCIDENTS.${id} has no window (R-11a)`);
  const responseRows = Object.entries(D.INCIDENTS).flatMap(([id, inc]) => inc.responses.map((r) => [`\`${id}\``, `\`${r.id}\``, r.label, usd(r.cost), r.score,
    r.walkupMult ?? '—', r.flowMult ?? '—']));

  const objCost = { stage: 'With the lot', 'pa-s': usd(D.PA_RENTAL.S), 'pa-m': usd(D.PA_RENTAL.M), lights: usd(D.LIGHTS_RENTAL), bar: usd(D.BAR_SETUP), food: 'Vendor funded', trailer: `${usd(D.SANITATION_COSTS.trailer)} + optional cleaner/utilities`, restroom: usd(D.RESTROOM_UNIT), gate: 'Free', exit: 'Free', fence: usd(D.FENCE_KIT) };
  const objStaff = { bar: `${D.BAR_STAFF_PER_BAR} bar`, gate: `${D.DOOR_STAFF_PER_GATE} door` };
  const objectRows = Object.entries(D.OBJECT_TYPES).map(([id, t]) => {
    const rules = [t.max ? `max ${t.max}` : null, t.edge ? 'on the boundary' : null, t.nextToStage ? 'touches the stage' : null, t.blocksSight ? 'blocks sightlines' : null, t.kit ? 'site-wide kit' : null].filter(Boolean).join(', ');
    if (!objCost[id]) problem(`tools/docs.mjs has no cost line for object ${id}`);
    return [`\`${id}\``, t.label, t.kit ? '—' : `${t.w} × ${t.h}`, t.watts ? `${t.watts / 1000} kW` : '—', objCost[id] || '', objStaff[id] || '—', rules || '—', M.BOARD_SPRITES[id] ? 'yes' : 'no'];
  });

  const rosterOf = (a) => D.VENUE_ORDER.filter((id) => D.VENUES[id].roster.includes(a)).map((id) => D.VENUES[id].name).join(', ');
  const actRows = Object.entries(D.ARTISTS).map(([id, a]) => [a.name, `\`${id}\``, a.genre, `${a.drawMin.toLocaleString('en-US')} to ${a.drawMax.toLocaleString('en-US')}`, usd(a.fairPrice), usd(a.ask), a.guaranteeOnly ? 'Guarantee only' : 'Either', rosterOf(id)]);

  // Types are the union over a new career, a new scenario and a game in show night.
  const samples = [E.createGame(1), E.createGame(1, { mode: 'scenario', scenario: 'wet-lot' }), stateInShow()];
  const typeOf = (v) => (v === null ? 'null' : Array.isArray(v) ? 'list' : typeof v);
  const stateRows = Object.keys(samples[0]).map((k) => {
    const types = [...new Set(samples.map((x) => typeOf(x[k])))].sort();
    const obj = samples.map((x) => x[k]).find((v) => v && typeof v === 'object' && !Array.isArray(v));
    return [`\`${k}\``, types.join(' or '), obj ? Object.keys(obj).map((x) => `\`${x}\``).join(', ') : ''];
  });

  return `${HEADER('Front of House Game Catalogue', 'Phases, actions and refusals are read from `engine.mjs`; the transition grid is played through the engine; content tables come from `data.mjs`.')}
The game's moving parts in one place: the phases a save can be in, every action that changes the game, what each action refuses and why, and every room, incident, object and act. [RULES.md](RULES.md) says how the numbers work; [SCREENS.md](SCREENS.md) says what the player sees; [SAVE_FORMAT.md](SAVE_FORMAT.md) says how state is stored.

## 1. Phases

Phases run in this order: ${E.PHASES.map((p) => `\`${p}\``).join(' → ')}. A loaded save is walked back to the last phase its contents support (\`normalizeState\`).

${table(['Phase', 'Screen', 'A save in this phase must hold'], E.PHASES.map((p) => [`\`${p}\``, PHASE_NOTES[p]?.screen, PHASE_NOTES[p]?.holds]))}

## 2. Actions

The client never changes state itself; it sends one of these to \`applyAction(state, action)\`, which returns the new state or the old one with an error. *Fields* are the action's inputs besides \`type\`.

${table(['Action', 'What it does', 'Fields', 'Allowed in', 'Moves to', 'Refusals'], actionRows)}

## 3. Transition grid

Each action sent from a reference game in each phase (seed 42, door deal, the suggested layout, $20, no ads, the incident answered with \`${firstResponse}\`). → names the phase it moves to, ✓ means accepted without a phase change, ✗ means refused with one of the messages in section 4.

${table(['From', ...ids.map((i) => `\`${i}\``)], matrix)}

\`chooseDoorCrew\` is refused here because the reference show is not in the opt-in doors trial (\`?night-slice=1\`).

## 4. Refusal messages

What the engine says when it refuses an action, as written in the source (\`\${…}\` is filled in at run time; *italic* lines describe a message the engine builds). Every action except \`back\` also refuses with "That can only be done during …" outside its phase, and any unknown action type is refused with "Unknown action".

${table(['Action', 'Message'], failRows)}

## 5. Modes

${table(['Mode', 'Starting cash', 'Forced incident', 'Lot at start', 'Rooms open'], modes)}

Sandbox skips the cash checks before doors and before the next show. Start over in a scenario restarts the scenario.

## 6. Rooms

${table(['Room', 'Id', 'Tier', 'Grid', 'Permit', 'Power', 'Rent + permit', 'PA', 'Seats', 'Nights', 'Incidents', 'Acts', 'Goal to move up'], roomRows)}

## 7. Incidents

Each show has one incident (R-11). *Window* is when it can happen, as a share of show night from doors at 19:00 to curfew at 23:00 (R-11a).

${table(['Id', 'Label', 'Window', 'Rooms'], incidentRows)}

${table(['Incident', 'Response', 'Label', 'Cost', 'Handling score', 'Walk-up ×', 'Entry flow ×'], responseRows)}

## 8. Objects

${table(['Id', 'Label', 'Footprint', 'Power', 'Cost', 'Staff', 'Placement rules', 'Sprite'], objectRows)}

## 9. Acts

${table(['Act', 'Id', 'Genre', 'Draws', 'Fair price', 'Ask', 'Deals', 'Rooms'], actRows)}

## 10. Saved state

The top level of a new game (\`createGame\`). Field meanings, validation and migrations are in [SAVE_FORMAT.md](SAVE_FORMAT.md).

${table(['Field', 'Type', 'Keys'], stateRows)}
`;
}

// ---------------------------------------------------------------------------
// STRINGS.md

// The named copy tables at the top of game.js. Each is evaluated with the same helpers the
// page uses, so a value that reads a number from data.mjs shows that number here.
const COPY_TABLES = [
  ['DEAL_HELP', 'Deal explanations (Book, Deals window)'],
  ['INCIDENT_TEXT', 'Incident card text (Show)'],
  ['RESPONSE_TEXT', 'Response consequences under each button (Show)'],
  ['TIPS', '"For next time" tips, by the weakest satisfaction part (Settlement)'],
  ['PART_LABELS', 'Satisfaction part names (Settlement)'],
  ['AD_LABELS', 'Ad channel names (Promote)'],
  ['COSTS', 'Tool costs (Build)'],
  ['SHORT', 'Tool tile names (Build)'],
  ['FACING', 'Rotation directions (Build)'],
];

function extractConst(src, name) {
  const at = src.search(new RegExp(`^const ${name} = `, 'm'));
  if (at < 0) return null;
  const open = src.indexOf('=', at) + 1;
  let depth = 0;
  let i = open;
  let started = false;
  for (; i < src.length; i += 1) {
    const c = src[i];
    if (c === '{' || c === '[' || c === '(') { depth += 1; started = true; }
    if (c === '}' || c === ']' || c === ')') depth -= 1;
    if (started && depth === 0) break;
  }
  return src.slice(open, i + 1).trim();
}

function stringsDoc() {
  const src = readFileSync(join(ROOT, 'game.js'), 'utf8');
  const helper = (name) => {
    const m = src.match(new RegExp(`^const ${name} = (.+);$`, 'm'));
    if (!m) { problem(`game.js has no one-line helper ${name}`); return 'null'; }
    return m[1];
  };
  const sandbox = { D };
  vm.createContext(sandbox);
  vm.runInContext(`var money = ${helper('money')};`, sandbox);
  const sections = COPY_TABLES.map(([name, where]) => {
    const code = extractConst(src, name);
    if (!code) { problem(`game.js has no copy table ${name}`); return ''; }
    const value = vm.runInContext(`(${code})`, sandbox);
    let rows;
    if (Array.isArray(value)) rows = value.map((v, i) => [i, v]);
    else rows = Object.entries(value).flatMap(([k, v]) => (v && typeof v === 'object' ? Object.entries(v).map(([k2, v2]) => [`${k} · ${k2}`, v2]) : [[k, v]]));
    return `### \`${name}\`: ${where}\n\n${table(['Key', 'Text'], rows.map(([k, v]) => [`\`${k}\``, v]))}`;
  }).join('\n\n');

  const labelRows = [
    ...Object.entries(D.OBJECT_TYPES).map(([id, t]) => ['Object', `\`${id}\``, t.label]),
    ...Object.entries(D.INCIDENTS).flatMap(([id, inc]) => [['Incident', `\`${id}\``, inc.label], ...inc.responses.map((r) => ['Response', `\`${id}\` · \`${r.id}\``, r.label])]),
    ...D.VENUE_ORDER.map((id) => ['Room', `\`${id}\``, D.VENUES[id].name]),
  ];

  const inline = (src.match(/`[^`]*[A-Za-z]{3,} [A-Za-z]{3,}[^`]*`|'[^'\n]*[A-Za-z]{3,} [A-Za-z]{3,}[^'\n]*'/g) || []).length;

  return `${HEADER('Front of House String Table', 'Copy tables are evaluated from `game.js`; labels come from `data.mjs`; refusals are in CATALOG.md.')}
Where the player-facing words live, so copy can be reviewed and changed in one pass. Change the text in the file named in each section, then regenerate.

## 1. Copy tables in \`game.js\`

${sections}

## 2. Labels in \`data.mjs\`

Names the engine, the board and the settlement sheet all use. Act names and genres are in [CATALOG.md](CATALOG.md#9-acts) and their name checks in [WORLD.md](WORLD.md).

${table(['Kind', 'Id', 'Label'], labelRows)}

## 3. Engine refusals

The messages shown when an action is refused are listed by action in [CATALOG.md](CATALOG.md#4-refusal-messages).

## 4. Not covered here

Headings, buttons, feed lines and sentences built inside \`game.js\`'s render functions are written inline, not in a table: about ${Math.round(inline / 10) * 10} string literals with words in them. Moving them into tables (and so into this file) is listed in [KNOWN_ISSUES.md](KNOWN_ISSUES.md).
`;
}

// ---------------------------------------------------------------------------

const outputs = {
  'ASSETS.md': assetsDoc(),
  'CATALOG.md': catalogDoc(),
  'STRINGS.md': stringsDoc(),
};

if (problems.length) {
  console.error(`front-of-house docs: ${problems.length} problem(s); nothing written.`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
for (const [name, text] of Object.entries(outputs)) {
  writeFileSync(join(DOCS, name), text);
  console.log(`wrote ${relative(REPO, join(DOCS, name))}`);
}
